### ISSUE TITLE
Google 3d Tiles Error (No such file or directory)

### ISSUE THREAD

**Issue by Julldozer119** [vvoovv/blender-geo#443] opened 2024-01-11 02:34 UTC
Hi ! 

I'm trying to use the 3D tiles but importing causes an error for me, on the other hand terrain and OSM works.

Blender 4.0 and Blosm 2.7.2

I get the errors : "There was an error when processing the URI" then  "No such file or directory".

I tried different folder without success. 

The error : 

![Capture3](https://github.com/vvoovv/blosm/assets/100882379/5d29da20-9fbd-4bdb-9a61-ea619b806cbb)

My settings : 

![Capture1](https://github.com/vvoovv/blosm/assets/100882379/8af9ff98-3a54-4c37-bc44-98d66e323e35)

and the directory : 

![Capture2](https://github.com/vvoovv/blosm/assets/100882379/25cadcce-c4e8-4d7d-964a-cdc6260fe7e9)

Thank you for your work !

**Comment by coastbluet** [comment] 2024-01-11 03:47
I've got the same problem. It was working for me about 8 hours ago, but then started giving this error. I tried a new blender install on a different computer and got the same thing.

**Comment by vvoovv** [comment] 2024-01-11 08:49
@Julldozer119, @coastbluet 

I can confirm the problem. It looks like Google has changed something recently. We are currently investigating the problem. I'll report back to you as soon as possible.

**Comment by vvoovv** [comment] 2024-01-11 10:43
A fix will be provided later today.

For now I can propose a quick fix;

* Open the Python Console:

![image](https://github.com/vvoovv/blosm/assets/613295/3593ae80-3c71-4640-9a6f-590e96dc3b8a)

* Paste the line below and press Enter:
``` Python
C.scene.blosm.cacheJsonFiles = False
```

**Comment by vvoovv** [comment] 2024-01-11 10:46
Below is the cause of the problem.

Google changed the naming of the files related to Google 3D tiles. The file names became a slightly longer. The total length of file names started to exceed the maximum file length on Windows.

**Comment by mendicus777** [comment] 2024-01-11 12:23
`C.scene.blosm.cacheJsonFiles = False`

Thanks! That did it

**Comment by TorgeirHolm** [comment] 2024-01-11 12:24
> A fix will be provided later today.
> For now I can propose a quick fix;
> * Open the Python Console:
> * Paste the line below and press Enter:
> C.scene.blosm.cacheJsonFiles = False

Thanks for the quick workaround!

**Comment by vvoovv** [comment] 2024-01-11 15:14
The latest version (2.7.3) with the fix has been uploaded. You can use the link in your purchase/download confirmation email to get it.

**Comment by Julldozer119** [comment] 2024-01-11 15:16
Thank you for the quick response and the fix !

**Comment by coastbluet** [comment] 2024-01-11 16:57
Thank you for fixing it so quickly

**Comment by IgorVe** [comment] 2024-01-18 15:35
Unfortunately still have this URI HTTP error 400 issue in  2.7.3 version...

**Comment by vvoovv** [comment] 2024-01-18 15:38
@IgorVe 

Your error is different. Please see the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.

**Comment by IgorVe** [comment] 2024-01-18 16:23
> @IgorVe
> 
> Your error is different. Please see the [FAQ](https://github.com/vvoovv/blosm/wiki/Import-of-Google-3D-Cities#faq) section of the documentation.

Just solved it. Thank you for a fast reply and good luck with a project. Will test it and if it works will buy a pro version.

**Comment by w45354** [comment] 2024-01-31 08:58
I have installed the latest version 2.7.4, but still have the error 10060. what might be the issue?
![cbbdb2fc1b29a6349b68ddb79af7e10](https://github.com/vvoovv/blosm/assets/157502002/4bf58b38-7158-4ba6-9b8e-727c5e04bcd6)

**Comment by vvoovv** [comment] 2024-01-31 10:34
Hi @w45354 

Your problem is different. It's a network problem. Please check your network settings, firewall, proxy, VPN, etc. Also there was a report that the addon BlenderKit blocked the network connection.

**Comment by JJEccles** [comment] 2024-10-11 08:27
I'm having this issue when trying to import the 3d tiles with my google api key:   in import3dTiles
    renderer = BlenderRenderer(
TypeError: BlenderRenderer.__init__() takes 3 positional arguments but 4 were given

Is anyone experiencing the same issue or know of a fix? Its a premium version of blosm that used to import fine before but i haven't used it in a while.

**Comment by vvoovv** [comment] 2024-10-11 09:37
@JJEccles

* Delete all version of Blender-OSM or Blosm addon. You can find them by typing _osm_ in the search field.
* Restart Blender
* Install the latest version of the Blosm addon (currently 2.7.9)

**Closed as completed by vvoovv** 2024-10-11 09:37 UTC

**Comment by hugopimentel100** [comment] 2024-11-21 20:52
@vvoovv I'm new to the program and I am having the same issue. I already tried uninstalling and reinstalling the program and add-on but nothing seems to work. Please advise, thanks

**Comment by vvoovv** [comment] 2024-11-21 21:05
Hi @hugopimentel100 

What version of Blender are are using?

Please also paste a screenshot of the error.

**Comment by hugopimentel100** [comment] 2024-11-22 12:37
I'm using Blender 4.3.0 and the latest Blosm. Here's the screenshot of the error:
![image](https://github.com/user-attachments/assets/33a5a54d-a77f-4c63-afe4-cdf0d24c5469)

**Comment by vvoovv** [comment] 2024-11-22 13:19
@hugopimentel100 

Please read #555

Sorry for the inconveniences.

**Comment by hugopimentel100** [comment] 2024-11-22 13:55
It worked - I copied the file as suggested. Thank you for your support!

**Comment by hugopimentel100** [comment] 2024-11-22 16:39
Quick update - it worked twice and then it stopped working. Blender freezes and I have to restart it. I will try to use blender 4.2

**Comment by vvoovv** [comment] 2024-11-22 16:41
@hugopimentel100 

Probably you chose a large area. Just wait a bit longer or chose a smaller area or a lower level of details.

**Comment by hugopimentel100** [comment] 2024-11-22 16:47
I was able to import a small area on my first trial after following the instruction on #555
On my second trial I successfully imported a much larger area with the highest level of detail
On my third trial I tried importing a smaller area than the area on the second trial, also highly detailed - it did not work.

For my second trial I waited for around 10 minutes. For my third trial (with a smaller area) I waited for over one hour and nothing happened.

**Comment by vvoovv** [comment] 2024-11-22 16:53
@hugopimentel100 

Open Blender's System Console (Window -> Toggle System Console) to check if the import is still running.

**Comment by hugopimentel100** [comment] 2024-11-22 17:34
I downloaded Blender 4.2 instead and it seems to be working fine now. I'm checking all import commands through the system console window for sanity check. Thank you for the support!

**Comment by ridation** [comment] 2024-12-30 15:12
I have the 2.7.11 which I think is the latest version but I still get this error:
"no 3d tiles were imported..."
![image](https://github.com/user-attachments/assets/ca1d14ec-c2db-4af8-aaa1-a7216b021140)

**Comment by vvoovv** [comment] 2024-12-30 15:17
Hi @ridation 

Please paste a screenshot of Blender's System Console:
Main Menu -> Window -> Toggle System Console

**Comment by ridation** [comment] 2024-12-30 15:42
![image](https://github.com/user-attachments/assets/69b6a2e7-49d7-41f6-8809-9b2546a46b6e)

**Comment by vvoovv** [comment] 2024-12-30 16:29
@ridation 

Please install the latest stable version of Blender (currently 4.3.2). See also #555.

**Comment by ridation** [comment] 2024-12-30 18:42
@vvoovv Thank you the problem is solved,
However, is there any way we can get a more flat surface for the buildings instead of these wavy ones? I used "building with more details" but still...
![image](https://github.com/user-attachments/assets/5a7d75ba-2f14-4e24-bb37-b71189561ae7)

**Comment by ridation** [comment] 2024-12-30 18:58
Or any chance to be able to deselect trees to only have buildings and street?

**Comment by vvoovv** [comment] 2024-12-30 21:18
@ridation 

That's what Google Cloud provides...

**Comment by johncgrayson** [comment] 2025-02-13 03:09
> The latest version (2.7.3) with the fix has been uploaded. You can use the link in your purchase/download confirmation email to get it.

Hey @vvoovv ! I don't see 2.7.3 on my account, only 2.7.11. Am I looking in the wrong place? Also the console code did not work for me.

**Comment by stefanobertelli1974** [comment] 2025-09-29 23:02
where i find 2.7.2 version or ,3? many tnx :)

**Comment by vvoovv** [comment] 2025-09-30 05:38
Hi @stefanobertelli1974 

We recommend always using the latest version of the Blosm addon (currently 2.7.17).

By the way, why do you need the version 2.7.2?

**Comment by StelianGrigorescu** [comment] 2026-03-30 20:44
2026 March and still have the same problems. I am able to import buildings with details, but when I set it to  buildings with "MORE" details I get 99 problems .
Blender 4.5 and last version of Blosm. This is stupid and I need a fix now, cause my deadline is near...

**Comment by vvoovv** [comment] 2026-03-30 20:52
Hi @StelianGrigorescu 

Please install the latest version of the Blosm addon (currently 2.7.24)

**Comment by StelianGrigorescu** [comment] 2026-03-31 03:58
Yeah, thanks man, for paying for an unresponssive software. By the way, why building with details is rubbish, and buildings with more details is not working even in the paid version? Building with details is like district geometry for me... I have 2000 errors, no import.

**Comment by vvoovv** [comment] 2026-03-31 07:12
@StelianGrigorescu
Could you please paste a screenshot of your Blosm preferences?
And then a screenshot with the errors?

**Comment by StelianGrigorescu** [comment] 2026-03-31 12:06
Finally it worked on my work pc, even tough is a personal project. But I let you know that there IS a difference between this 3d resolution and what Google Maps has, mainly of texture resolution, wich is obvious and not good. But thanks, anyway, dude, for your work.

<img width="3282" height="1669" alt="Image" src="https://github.com/user-attachments/assets/d70ffeab-1add-41f0-abf5-a3788a022ba5" />

**Comment by vvoovv** [comment] 2026-03-31 13:41
@StelianGrigorescu 
Please note that Google Maps and Google 3D Tiles are two different data sets. Google Maps do provide a better resolution in comparison with Google 3D Tiles
