### ISSUE TITLE
A valid directory for a Blender file with materials for buildings isn't set

### ISSUE THREAD

**Issue by MikePG7** [vvoovv/blender-geo#105] opened 2018-09-30 22:25 UTC
I am installing the blender-osm addon. It is asking me to set a 'Directory to store downloaded OpenStreetMap and terrain files'. I have tried to do this about 20 times, but every time I get this error message:  
"A valid directory for a Blender file with materials for buildings isn't set"
Any suggestions?

**Comment by vvoovv** [comment] 2018-09-30 23:01
Please send a screenshot with the addon preferences (similar to [that one](https://raw.githubusercontent.com/wiki/vvoovv/blender-osm/images/installation.png)) to prokitektura+support@gmail.com

**Comment by MikePG7** [comment] 2018-10-01 20:47
Here are 4 screenshots.

**Comment by vvoovv** [comment] 2018-10-01 20:53
@MikePG7 
I have edited your message since it contained your private information.

You probably forgot to attach the screenshots.
Please send them to prokitektura+support@gmail.com
Or attach them directly at the github using the link https://github.com/vvoovv/blender-osm/issues/105, so your private information won't be exposed.

**Comment by MikePG7** [comment] 2018-10-01 20:57
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by vvoovv** [comment] 2018-10-01 21:01
Still no attachments :(

Could you please send the screenshots to prokitektura+support@gmail.com ?

**Comment by MikePG7** [comment] 2018-10-01 21:01
Third time lucky?
![1](https://user-images.githubusercontent.com/17655154/46315488-870ff800-c5c5-11e8-8547-6d012937476c.png)
![2](https://user-images.githubusercontent.com/17655154/46315489-870ff800-c5c5-11e8-84a7-7e382a097cb9.png)
![3](https://user-images.githubusercontent.com/17655154/46315490-87a88e80-c5c5-11e8-9758-b424d2294963.png)
![4](https://user-images.githubusercontent.com/17655154/46315492-87a88e80-c5c5-11e8-9fee-55ff0b864932.png)



Sorry, Here are the screenshots (3rd time lucky?)

**Comment by vvoovv** [comment] 2018-10-01 21:06
Does the directory C:\blender\data really exist?

**Comment by MikePG7** [comment] 2018-10-01 21:09
I think so – see attached screenshot 5

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by vvoovv** [comment] 2018-10-01 21:11
No screenshot 5 again :(

**Comment by MikePG7** [comment] 2018-10-01 21:11
Darn - Let's try again...
![5](https://user-images.githubusercontent.com/17655154/46316067-f63a1c00-c5c6-11e8-9f28-0645b9289876.png)

**Comment by MikePG7** [comment] 2018-10-01 21:22
Hi - did you get screenshot 5 showing file location?

________________________________

**Comment by vvoovv** [comment] 2018-10-01 21:25
Yes
I will contact you via e-mail in order not to expose private information.

**Comment by vvoovv** [comment] 2018-10-01 21:43
Just realized the cause of the problem. I should have paid more attention to the error message in the screenshot.

The error message is about missing Blender file with materials. The file is set in the field (q) on the screenshot:
![image](https://user-images.githubusercontent.com/613295/46317554-11635680-c5dc-11e8-8171-65158f20834d.png)

There is a misprint in the error message. It should be "file" rather than "directory ". I am sorry for that.

**Comment by vvoovv** [comment] 2018-10-02 00:40
That field should be set to the file _assets/materials.blend_

**Comment by nafergo** [comment] 2018-12-02 18:38
I have the same error but I don't have that "q" field in my version. 
![screenshot from 2018-12-02 18-34-57](https://user-images.githubusercontent.com/6432502/49343456-69ace800-f661-11e8-9bab-8e657bbba15e.png)
![screenshot from 2018-12-02 18-35-17](https://user-images.githubusercontent.com/6432502/49343457-6dd90580-f661-11e8-91ff-0b5462fdf8b3.png)
![screenshot from 2018-12-02 18-36-33](https://user-images.githubusercontent.com/6432502/49343458-6fa2c900-f661-11e8-859f-3f9763792b55.png)

**Comment by vvoovv** [comment] 2018-12-02 19:13
@nafergo 
The latest version of the blender-osm (base) is 2.3.9. Please download and install the latest version using the download link from your purchase confirmation e-mail.
[Installation instructions](https://github.com/vvoovv/blender-osm/wiki/Documentation#installation)

**Comment by nafergo** [comment] 2018-12-03 10:52
Using 2.3.190.
Still have a similar error message. "A valid Blender file with materials for buildings isn't set!"
I don't have the "q" field to set it up.

**Comment by vvoovv** [comment] 2018-12-03 11:39
Please ensure that you use the latest stable Blender release from https://www.blender.org/download/

**Comment by nafergo** [comment] 2018-12-03 11:48
Seems to work with stable 2.79b. I was using daily build.

**Comment by vvoovv** [comment] 2018-12-03 11:56
The following Python code behaves differently in Python 3.5.3 (stable Blender 2.79b) and Python 3.7.0 (Blender 2.8 and daily builds). That's the reason of the problem.
``` python
class C:
    a = (1,)
    b = (1,)
C.a is C.b

```
<pre>
# in Python 3.5.3:
>>> C.a is C.b
False
</pre>

<pre>
# in Python 3.7.0
>>> C.a is C.b
True
</pre>
I'll fix it in the the next release.

**Comment by KitzigID** [comment] 2019-07-12 09:37
Hi I am getting a similar error message. I tried Blender 2.79 and 2.80. See attached screenshots.
I think I installed it correct but I always get that error message.

![2019-07-12_10-46-32](https://user-images.githubusercontent.com/52818891/61118536-38b75000-a499-11e9-8140-45f49f487b3c.jpg)

![2019-07-12_10-47-58](https://user-images.githubusercontent.com/52818891/61118571-4b318980-a499-11e9-9365-5e011a4a7519.jpg)

![2019-07-12_11-33-05](https://user-images.githubusercontent.com/52818891/61118579-4f5da700-a499-11e9-9c70-bc35d0c697a4.jpg)

![2019-07-12_11-34-28](https://user-images.githubusercontent.com/52818891/61118582-52f12e00-a499-11e9-938a-9813d4485e22.jpg)

**Comment by MlleDR** [comment] 2019-08-12 09:24
Hi @vvoovv , I just bought the premium version and I have the same errors with this log :

### > The directory with assets ***\FromBlender\Models\OpenStreetMaps\Assets doesn't contain the file building_materials.blend. Please set a directory with assets (building_materials.blend, vegetation.blend) in the addon preferences or addon GUI!

I have the following directories in the User settings:
![image](https://user-images.githubusercontent.com/27687330/62855458-976b2600-bcf2-11e9-9c77-05729e878e5d.png)

And my osm toolbar
![image](https://user-images.githubusercontent.com/27687330/62855505-bc5f9900-bcf2-11e9-8caa-f75e98f9c715.png)

- In my first attempt, I did not reference the asset directory path in the toolbar.
![image](https://user-images.githubusercontent.com/27687330/62855890-b0280b80-bcf3-11e9-84de-fa451b59ee93.png)

- After reading this post, I did this and try to copy a new map again. (_Select_ --> _Choose a map_ --> _Copy_ and then _Import_ in the toolbar). But I still have the same error.

Could you help me please? Thanks in advance.

**Comment by vvoovv** [comment] 2019-08-12 10:24
Hi @MlleDR 
Thank you for purchasing the blender-osm addon!

I'd recommend to set the directory with assets only in one place, either in the addon preferences or in the addon panel (setting it in the addon preference is a better choice).

Please check if your folder for assets does contain the file _building_materials.blend_. If not, please unpack the zip-archive _assets.zip_ and set that setting to the unpacked folder.

**Comment by MlleDR** [comment] 2019-08-12 11:25
Thank you for the quick reponse! As you told, I set only the Directory with asset path:

![image](https://user-images.githubusercontent.com/27687330/62861867-08b3d480-bd05-11e9-98f0-8839a49a73b5.png)

Indead I have no in this folder (which is empty).

Question : When you speak of _assets.zip_, are you talking about assets folder in **blender-osm.zip** ? Because I had no _assets.zip_ file after purchasing the tool.

![image](https://user-images.githubusercontent.com/27687330/62861662-77dcf900-bd04-11e9-871e-60e18e877fa0.png)

Edit - here are the contents of this folder.
![image](https://user-images.githubusercontent.com/27687330/62861788-d3a78200-bd04-11e9-9986-32c1f855e458.png)

**Comment by vvoovv** [comment] 2019-08-12 12:47
@MlleDR,
If you follow the download link in the purchase confirmation e-mail, you see two files: 
* _blender-osm.zip_
* _assets.zip_

Please download and unpack the file _assets.zip_

**Comment by MlleDR** [comment] 2019-08-13 08:19
Hello @vvoovv , you were right, I did not see the assets.zip. I did as you told and did have another error.

`A valid directory for data in the addon preferences isn't set.`

So I added a path in _Directory to store Downloaded OpenStreetMaps and terrain files_, and guess what ;) 

Many thanks for your help! This is a hell of a tool!

**[FIXED in Blender 2.80]**

**Comment by vvoovv** [comment] 2019-08-13 08:26
@MlleDR,
Great news!
I am glad that the addon works for you!

**Closed as completed** 2020-02-18 14:24 UTC
